# Generated by Django 5.0.6 on 2024-05-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruit', '0003_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default=0.0004945598417408506, max_length=254),
            preserve_default=False,
        ),
    ]
